### PR TITLE
fix logout button

### LINKED ISSUE #69: fix logout button in all pages
not working

### PR DESCRIPTION
**Pull request by Omer-Levi**
## Why:
Closes #69

## What's being changed:
fix logout button

### CODE REVIEW

**Review by Ofek258 — DISMISSED** [review]
LGTM

**Review by Ofek258 — DISMISSED** [review]
LGTM

**Review by ofirtzabari — DISMISSED** [review]
good

**Review by ofirtzabari — APPROVED** [review]
good

**Review by Ofek258 — APPROVED** [review]
LGTM

**Pull request merged**
